<?php

/**
 * Implements hook_menu().
 */
function schools_menu() {
/**
 * Sample code from the api example.
 *  items['blog'] = array(
 *    'title' => 'blogs',
 *    'page callback' => 'blog_page',
 *    'access arguments' => array('access content'),
 *    'type' => MENU_SUGGESTED_ITEM,
 *);
 *return items;
 */

 /* Your code here */
 $items = array();
 $items['schools'] = array(
   'title' => 'Schools',
   'page callback' => 'schools_overview_page',
   'access callback' => TRUE
 );
 $items['schools/create'] = array(
  'title' => 'Schools Form',
  'page callback' => 'schools_form_page',
  'access callback' => TRUE
);

 return $items;

}

/**

 * Implements hook_init().

 */

function schools_init() {
  // Prevent the page from being cached.
  // drupal_page_is_cacheable(FALSE);
  // drupal_flush_all_caches();
}

function schools_overview_page() {

  $records = db_query('SELECT * FROM {schools}')->fetchAllAssoc('school_id');

  // dpm($records);
  // dpm(gettype($records));
  // return array();
  function getSchoolName($school)
  {
    return($school->name);
  }

  $names = array_map('getSchoolName', $records);
    
  return array(
    '#type' => 'container',
    'schools' => array(
      '#theme' => 'item_list',
      '#items' => $names,
    ),
  );

}


function schools_form_page() {
  $form = drupal_get_form('schools_create_school_form');
  // dpm($form);

  return $form;
}

function schools_create_school_form($form, &$form_state) {
  $form['title'] = array(
    '#markup' => '<h2>Register a school</h2>',
  );
  $form['name'] = array(
    '#type' => 'textfield', 
    '#title' => 'School Name',   
    '#maxlength' => 255, 
    '#required' => TRUE,
  );
  $form['address'] = array(
    '#type' => 'textfield', 
    '#title' => 'School Address',   
    '#maxlength' => 255, 
    '#required' => TRUE,
  );
  $form['zip'] = array(
    '#type' => 'textfield', 
    '#title' => 'Zip Code',   
    '#maxlength' => 10, 
    '#required' => TRUE,
  );
  $form['submit'] = array(
    '#type' => 'submit', 
    '#value' => 'Submit',
  );
  $form['#attached']['css'] = array(
    drupal_get_path('module', 'schools') . '/css/schools_form.css',
  );
  return $form;
}

/**
 * Implements validation from the Form API.
 * 
 * @param $form
 *   A structured array containing the elements and properties of the form.
 * @param $form_state
 *   An array that stores information about the form's current state 
 *   during processing.
 */
function schools_create_school_form_validate($form, &$form_state) {
  // dpm($form_state);
  $values = &$form_state['values'];
  $name = $values['name'];
  $address = $values['address'];
  $zip = $values['zip'];

  if (strlen($name) > 255){
    form_set_error('name', 'Length of name field must be less than 255.');
  }

  if (strlen($address) > 255){
    form_set_error('address', 'Length of address field must be less than 255.');
  }

  if (strlen($zip) != 5){
    form_set_error('zip', 'Zip code must be of length 5.');
  }

  if(!is_numeric($zip)) {
    form_set_error('zip', 'Zip code cannot contain nonnumeric values');
  }
}

function schools_create_school_form_submit($form, &$form_state) {
  // dpm('submit');
  // dpm($form_state);
  $values = &$form_state['values'];
  $name = $values['name'];
  $address = $values['address'];
  $zip = $values['zip'];
  db_insert('`schools`')
    ->fields(array('name', 'address', 'zip'))
    ->values(array(
        'name' => $name,
        'address' => $address,
        'zip' => $zip,
        ))
    ->execute();  
}