<?php

/**
 * Implements hook_menu().
 */
function schools_menu() {
/**
 * Sample code from the api example.
 *  items['blog'] = array(
 *    'title' => 'blogs',
 *    'page callback' => 'blog_page',
 *    'access arguments' => array('access content'),
 *    'type' => MENU_SUGGESTED_ITEM,
 *);
 *return items;
 */

 /* Your code here */
 $items = array();
 $items['schools'] = array(
   'title' => 'Schools Overview',
   'description' => 'Schools overview page',
   'page callback' => 'schools_overview',
   'access callback' => TRUE
 );

 return $items;

}


function schools_overview() {
  return array(
    '#markup' => '<p>This is the school overview page test</p>'
  );
}
